### ISSUE TITLE
pip install python-hoverfly-wrapper fails

### ISSUE THREAD

**Issue by pjgoodall** [kopernio/pytest-hoverfly-wrapper#21]
Install from pip fails when following instructions. There appears to be a **typo in the instructions** on pypi and github.

you have `pip install python-hoverfly-wrapper`

it should be: `pip install pytest-hoverfly-wrapper` 
**which also fails.**

the `git clone <> && cd <> && python setup.py install` thing does work

Platform:
```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

```
% pip --version                      
pip 20.3.3 from /home/peterg/miniconda3/envs/py-hov-wrapper/lib/python3.8/site-packages/pip (python 3.8)
```

hoverfly is installed as described in documentation
```
> which hoverfly
/home/me/bin/hoverfly
> which hoverctl
/home/me/bin/hoverctl
```

```
>conda create -n py-hov-wrapper python=3.8
>conda activate  py-hov-wrapper
(py-hov-wrapper)> pip install python-hoverfly-wrapper

ERROR: Could not find a version that satisfies the requirement python-hoverfly-wrapper
ERROR: No matching distribution found for python-hoverfly-wrapper
```
whereas the `git clone`, `python setup.py install` works in the same conda environment.

**Comment by veliakiner** [comment]
Hi Peter, thanks for raising the issue and highlighting the typo. I can't reproduce the inability to install `pytest-hoverfly-wrapper` via `pip` in a conda environment - at the end of your report you're still attempting to install `python-hoverfly-wrapper`. Is it possible that when the installation failed you were still trying to install the package with the typo?

**Comment by pjgoodall** [comment]
Yes, I think you are right.
